Fix GCC-14 compilation warning.
third_party/fmt/include/fmt/ranges.h:215:59: error: self-comparison always evaluates to true [-Werror=tautological-compare]
  215 |                                integer_sequence<bool, (Is == Is)...>);

 Is == Is is always true. Upstream uses Is >=0 which is more meaningful to check non-negative
 index values.

 https://github.com/fmtlib/fmt/blob/cc2ba8f9ede4e5ae3262f43f3e4d07a22a9acdfc/include/fmt/ranges.h#L162