Ignore format-truncation warning
With clang-17 compilation fails due to:

src/type/timestamp_type.cpp:130:29: error: ‘%02d’ directive output may be truncated writing between 2 and 10 bytes into a region of size 5 [-Werror=format-truncation=]

Until it gets a proper fix, ignore this warning.